theme: jekyll-theme-cayman
title: Taro ODASHIMA
description: A full-stack web engineer, and also an amateur magician!
lang: ja

path:
  base: /
  img: /assets/img/

sns:
- title: Twitter
  url: https://twitter.com/shimataro999
  img: twitter.svg
- title: Facebook
  url: https://www.facebook.com/odashima.taro
  img: facebook.svg
- title: LINE
  url: https://line.me/ti/p/shimataro777
  img: line.svg
- title: GitHub
  url: https://github.com/shimataro
  img: github.svg
- title: Qiita
  url: https://qiita.com/shimataro999
  img: qiita.svg

defaults:
- scope:
    path: "assets/img"
  value:
    image: true

show_downloads: false
github:
  is_project_page: false
