theme: jekyll-theme-cayman
title: Taro ODASHIMA
description: A full-stack web engineer, and also an amateur magician!
lang: ja

google_analytics: UA-150079955-1

path:
  base: /
  img: /assets/img/

sns:
- title: Twitter
  url: https://twitter.com/shimataro999
  img: twitter.svg
- title: Facebook
  url: https://www.facebook.com/odashima.taro
  img: facebook.svg
- title: LinkedIn
  url: https://www.linkedin.com/in/odashima-taro/
  img: linkedin.svg
- title: Messenger
  url: https://m.me/odashima.taro
  img: messenger.svg
- title: Telegram
  url: https://t.me/shimataro
  img: telegram.svg
- title: LINE
  url: https://line.me/ti/p/bCc09e9jFB
  img: line.svg

defaults:
- scope:
    path: "assets/img"
  value:
    image: true

show_downloads: false
github:
  is_project_page: false
